---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sme33/public_html
    - /bin/rm -rf $DEPLOYPATH/*
    #- /bin/cp -R src $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH
    - /bin/cp /home/sme33/repositories/secure/skills.json~bak $DEPLOYPATH/skills.json
    - /bin/cp /home/sme33/py.sme.3-3.info/distro.json $DEPLOYPATH/distro.json
    #- /bin/bash /home/sme33/public_html/dev/build.sh
    #- ^^ should be made manually
